zsh-users/zsh-completions
zsh-users/zsh-autosuggestions
hanjunlee/terraform-oh-my-zsh-plugin
romkatv/powerlevel10k
tolbertam/hyper-font-ligatures
changyuheng/zsh-interactive-cd
#athityakumar/colorls
zsh-users/zsh-syntax-highlighting
zsh-users/zsh-history-substring-search
desyncr/vagrant-zsh-completion
