#!/bin/zsh

# load all files from .shell/zshrc.d directory
if [ -d $HOME/.zshrc.d ]; then
  for file in $HOME/.zshrc.d/*.zsh; do
    if [[ "$file" == *"plugins.zsh"* ]]; then
      continue
    else
      source $file
    fi
  done
fi
