---
- name: Download chezmoi install script
  get_url:
    url: https://git.io/chezmoi
    dest: /tmp/chezmoi.sh
    mode: 0755

- name: Execute chezmoi install script
  shell: /tmp/chezmoi.sh

- name: Remove chezmoi install script
  file:
    path: /tmp/chezmoi.sh
    state: absent
