---
- name: Download fzf install script
  git:
    repo: https://github.com/junegunn/fzf.git
    dest: /tmp/fzf

- name: Execute fzf install script
  shell:
    cmd: ./install --bin
    chdir: /tmp/fzf/

- name: Remove fzf install script
  file:
    path: /tmp/fzf/
    state: absent
