# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
#
# TL;DR setup:
#
# 1. brew install pre-commit
# 2. pre-commit install

fail_fast: true

repos:
  - repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      # Prevent giant files from being committed
      - id: check-added-large-files
      # Forbid files which have a UTF-8 byte-order marker
      - id: check-byte-order-marker
      # Check for files that would conflict in case-insensitive filesystems
      - id: check-case-conflict
      # Ensures that (non-binary) executables have a shebang.
      - id: check-executables-have-shebangs
      # Check for files that contain merge conflict strings.
      - id: check-merge-conflict
      # Checks for symlinks which do not point to anything.
      - id: check-symlinks
      # This hook checks toml files for parseable syntax.
      - id: check-toml
      # This hook checks xml files for parseable syntax.
      - id: check-xml
      # This hook checks yaml files for parseable syntax.
      - id: check-yaml
      # Detects the presence of private keys
      - id: detect-private-key
      # Makes sure files end in a newline and only a newline.
      - id: end-of-file-fixer
      # Sorts simple YAML files which consist only of top-level keys, preserving comments and blocks.
      - id: sort-simple-yaml
      # This hook trims trailing whitespace.
      - id: trailing-whitespace

  - repo: git://github.com/Yelp/detect-secrets
    rev: v0.13.0
    hooks:
      - id: detect-secrets
        args: ["--baseline", ".secrets.baseline"]
